# Generated by Django 5.0.6 on 2024-06-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
